---
title: "Project Proposal"
author: "Jack Kincannon"
date: "12/3/2020"
output: pdf_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="blog-link" class="section level1">
<h1>Blog Link</h1>
<p>My blog is available at <a href="https://jdkincan.netlify.app/" class="uri">https://jdkincan.netlify.app/</a></p>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre><code>## Warning: 1 parsing failure.
##    row col   expected    actual                                                    file
## 898078  -- 21 columns 5 columns &#39;/home/jdkincan/DASC1104_PROJ/jdk/data/blkjckhands.csv&#39;</code></pre>
<pre><code>## Warning: 2 parsing failures.
##    row  col   expected    actual                                                       file
## 618445 date date like  2015-09   &#39;/home/jdkincan/DASC1104_PROJ/jdk/data/all_stocks_5yr.csv&#39;
## 618445 NA   7 columns  1 columns &#39;/home/jdkincan/DASC1104_PROJ/jdk/data/all_stocks_5yr.csv&#39;</code></pre>
</div>
<div id="dataset-exploration" class="section level1">
<h1>Dataset Exploration</h1>
<div id="blackjack-analysis" class="section level2">
<h2>Blackjack Analysis</h2>
<pre class="r"><code>glimpse(dat1)</code></pre>
<pre><code>## Observations: 898,078
## Variables: 21
## $ X1          &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, …
## $ PlayerNo    &lt;chr&gt; &quot;Player1&quot;, &quot;Player2&quot;, &quot;Player3&quot;, &quot;Player4&quot;, &quot;Player5&quot;, &quot;P…
## $ card1       &lt;dbl&gt; 7, 10, 9, 2, 10, 6, 10, 3, 10, 9, 10, 3, 10, 9, 5, 10, 2,…
## $ card2       &lt;dbl&gt; 10, 9, 8, 10, 2, 1, 4, 10, 2, 6, 4, 5, 2, 10, 1, 10, 9, 5…
## $ card3       &lt;dbl&gt; 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 2, 0, 0, 10, 0, 1, 0, 0,…
## $ card4       &lt;dbl&gt; 0, 0, 0, 5, 5, 10, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 5,…
## $ card5       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ sumofcards  &lt;dbl&gt; 17, 19, 17, 17, 17, 25, 14, 13, 12, 15, 14, 14, 12, 19, 1…
## $ dealcard1   &lt;dbl&gt; 10, 10, 10, 10, 10, 10, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …
## $ dealcard2   &lt;dbl&gt; 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 8, …
## $ dealcard3   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 0, …
## $ dealcard4   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,…
## $ dealcard5   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ sumofdeal   &lt;dbl&gt; 18, 18, 18, 18, 18, 18, 23, 23, 23, 23, 23, 23, 26, 26, 2…
## $ blkjck      &lt;chr&gt; &quot;nowin&quot;, &quot;nowin&quot;, &quot;nowin&quot;, &quot;nowin&quot;, &quot;nowin&quot;, &quot;nowin&quot;, &quot;no…
## $ winloss     &lt;chr&gt; &quot;Loss&quot;, &quot;Win&quot;, &quot;Loss&quot;, &quot;Loss&quot;, &quot;Loss&quot;, &quot;Loss&quot;, &quot;Win&quot;, &quot;Wi…
## $ plybustbeat &lt;chr&gt; &quot;Beat&quot;, &quot;Plwin&quot;, &quot;Beat&quot;, &quot;Beat&quot;, &quot;Beat&quot;, &quot;Bust&quot;, &quot;DlBust&quot;…
## $ dlbustbeat  &lt;chr&gt; &quot;Dlwin&quot;, &quot;Beat&quot;, &quot;Dlwin&quot;, &quot;Dlwin&quot;, &quot;Dlwin&quot;, &quot;PlBust&quot;, &quot;Bu…
## $ plwinamt    &lt;dbl&gt; 0, 20, 0, 0, 0, 0, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20…
## $ dlwinamt    &lt;dbl&gt; 10, 0, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ ply2cardsum &lt;dbl&gt; 17, 19, 17, 12, 12, 7, 14, 13, 12, 15, 14, 8, 12, 19, 6, …</code></pre>
<p>For this project, I am examining a dataset that contains 90,000 blackjack hands with 6 players per hand. The data is stored in the blkjckhands.csv and it was downloaded from a repository on Kaggle that is linked below. The data consists of 898,078 observations of 21 variables. The variables X1 and PlayerNo describe the 6 players present in each hand, they are dbl numeric and a character string respectively. The variables: card1, card2, card3, card4, card5, dealcard1, dealcard2, dealcard3, dealcard4, and dealcard5 describe the numeric value of the card dealt. The number at the end of the variables corresponds to which card was dealt first in the sequence, if no card is dealt 0 takes the place of NA. Variables sumofcards and sumofdeal are numerics which total the value of the cards dealt to each player and the dealer, per hand, respectively. Blkjck is a simple character string with two unique values
nowin and Win. Winloss describes each players outcome simplistically per hand. Character values Loss and Win are the two options. Variables plybustbeat and dlbustbeat describe the hand outcome in more detail with unique values Beat, Plwin, Bust, DlBust, and Push for plybustbeat with Dlwin, Beat, PlBust, Bust, and Push for dlbustbeat. Each of these variables are class character. Plwinamt and dlwinamt describe the hand outcome monetarily. These values are numeric and a base bet of $10 is assumed for each player each hand. The final variable play2cardsum is interesting. It describes the starting position from which blackjack players make their decision. It represents the sum of card1 and card2 numerically.</p>
<p>Initial exploration and experience makes me look towards dealcard1 and ply2cardsum as two potential explanatory variables. This dataset is a wealth of information and I am sure that I will be able to analyze any angle of blackjack strategy and probability.</p>
<ul>
<li><p>Question 1: First, I want to see what the win probabilities are for a player based on the hand they are dealt, and see how these probabilities change through the course of a hand i.e when the dealers up card is factored in. For experimentation summary statistics will be calculated for critical values, which will then be visualized and compared using ggplot.</p></li>
<li><p>Question 2: Second, based on these probabilities I intend to calculate an optimal strategy. This strategy To investigate this, tables that describe the probability of a win will be produced, visualizations will be produced that track the difference between an optimal and sub-optimal strategy.</p></li>
<li><p>Question 3: Third, now that we know the best way to play the game, how can we maximize the expected value and profit of a given player? I will utilize various mathematical betting sequences such as the as the Fibonacci to determine the answer to this question. Visualizations will analyze how large of a difference a true understanding of a game makes in outcomes.</p></li>
</ul>
<p>The overarching purpose of this analysis is to show how optimized strategy is essential to making the most out of any market or game. I was inspired by Micheal Lewis books Moneyball and The Undoing Project, which are based around this idea.</p>
<p><a href="https://www.kaggle.com/mojocolors/900000-hands-of-blackjack-results" class="uri">https://www.kaggle.com/mojocolors/900000-hands-of-blackjack-results</a></p>
</div>
<div id="sp-500-analysis" class="section level2">
<h2>S&amp;P 500 Analysis</h2>
<pre class="r"><code>glimpse(dat2)</code></pre>
<pre><code>## Observations: 618,445
## Variables: 7
## $ date   &lt;date&gt; 2013-02-08, 2013-02-11, 2013-02-12, 2013-02-13, 2013-02-14, 2…
## $ open   &lt;dbl&gt; 15.07, 14.89, 14.45, 14.30, 14.94, 13.93, 14.33, 14.17, 13.62,…
## $ high   &lt;dbl&gt; 15.12, 15.01, 14.51, 14.94, 14.96, 14.61, 14.56, 14.26, 13.95,…
## $ low    &lt;dbl&gt; 14.63, 14.26, 14.10, 14.25, 13.16, 13.93, 14.08, 13.15, 12.90,…
## $ close  &lt;dbl&gt; 14.75, 14.46, 14.27, 14.66, 13.99, 14.50, 14.26, 13.33, 13.37,…
## $ volume &lt;dbl&gt; 8407500, 8882000, 8126000, 10259500, 31879900, 15628000, 11354…
## $ Name   &lt;chr&gt; &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;, &quot;AAL&quot;,…</code></pre>
<p>For this analysis, I am examining a dataset that contains 5 years worth of data from the S&amp;P 500 from 2013-2018. The data is stored in all_stocks_5yr.csv and it was downloaded from a repository on Kaggle that is linked below. The data consists of 618,445 observations of 7 variables. The variable date represents the trading day in question and is stored as a date. Variables open, high, low, and close represent the price in USD of the stock on one trading day. They are all stored as numeric values. Open is the price at market open, close at market close, and high and low represent the range of prices on that day. The variable volume represents the amount of shares bought and sold per ticker per day, it is a numeric. Name represents the stock ticker symbol, they are stored as characters and there are 506 unique values.</p>
<p>Through initial exploration, I stumbled onto the package TTR. It is a wealth of computational finance functions and information. I hope to use the tools available in this package to draw insights that would have previously been beyond my reach. For the purposes of this analysis I will select one ticker to analyze vs the market, and my starting capital will be $100,000.</p>
<ul>
<li><p>Question 1: How can I predict the direction of stock price? First, I plan on using TTR to create new variables RSI, Bollinger Bands, Momentum, Volatility, and MACD. These variables will all be numeric values. These variables are all indicators used in financial analysis and fall into four categories: trend, momentum, volume, and volatility. I will examine these indicators, their meanings, and what value they bring to the table. For visualization I will plot the indicator values over time, as well as the profit signals.</p></li>
<li><p>Question 2: Second, based on these probabilities of profit what is the best strategy? This strategy will essentially combine all the buying and selling signals of the chosen indicators. I can then create visualizations that show when the optimal time to buy and sell are.</p></li>
<li><p>Task 3: Lastly, I hope log the individual transactions that will take place. I will be using an all-in stop-loss strategy where 100% of my portfolio value is invested each time a trade is placed. If I can muster it, I will create a function that takes a date range as an input and outputs transactions, and profit.</p></li>
</ul>
<p>The overarching purpose of this analysis is to build a foundation for algorithmic trading. I hope to be able to build a live data algorithm by graduation and I believe this is an important step.</p>
<p><a href="https://www.kaggle.com/camnugent/sandp500" class="uri">https://www.kaggle.com/camnugent/sandp500</a></p>
</div>
<div id="nba-shot-analysis" class="section level2">
<h2>NBA Shot Analysis</h2>
<pre class="r"><code>glimpse(dat3)</code></pre>
<pre><code>## Observations: 200,966
## Variables: 24
## $ GRID_TYPE           &lt;chr&gt; &quot;Shot Chart Detail&quot;, &quot;Shot Chart Detail&quot;, &quot;Shot C…
## $ GAME_ID             &lt;chr&gt; &quot;0020900001&quot;, &quot;0020900001&quot;, &quot;0020900001&quot;, &quot;002090…
## $ GAME_EVENT_ID       &lt;dbl&gt; 2, 3, 5, 6, 7, 9, 10, 12, 14, 16, 18, 23, 25, 27,…
## $ PLAYER_ID           &lt;dbl&gt; 2760, 951, 2544, 708, 2760, 2544, 951, 2760, 2590…
## $ PLAYER_NAME         &lt;chr&gt; &quot;Anderson Varejao&quot;, &quot;Ray Allen&quot;, &quot;LeBron James&quot;, …
## $ TEAM_ID             &lt;dbl&gt; 1610612739, 1610612738, 1610612739, 1610612738, 1…
## $ TEAM_NAME           &lt;chr&gt; &quot;Cleveland Cavaliers&quot;, &quot;Boston Celtics&quot;, &quot;Clevela…
## $ PERIOD              &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ MINUTES_REMAINING   &lt;dbl&gt; 11, 11, 11, 10, 10, 10, 9, 9, 9, 9, 8, 8, 8, 8, 8…
## $ SECONDS_REMAINING   &lt;dbl&gt; 31, 12, 3, 46, 26, 6, 45, 36, 27, 6, 54, 35, 15, …
## $ EVENT_TYPE          &lt;chr&gt; &quot;Made Shot&quot;, &quot;Missed Shot&quot;, &quot;Made Shot&quot;, &quot;Made Sh…
## $ ACTION_TYPE         &lt;chr&gt; &quot;Step Back Jump shot&quot;, &quot;Jump Shot&quot;, &quot;Jump Shot&quot;, …
## $ SHOT_TYPE           &lt;chr&gt; &quot;2PT Field Goal&quot;, &quot;2PT Field Goal&quot;, &quot;2PT Field Go…
## $ SHOT_ZONE_BASIC     &lt;chr&gt; &quot;In The Paint (Non-RA)&quot;, &quot;Mid-Range&quot;, &quot;Mid-Range&quot;…
## $ SHOT_ZONE_AREA      &lt;chr&gt; &quot;Center(C)&quot;, &quot;Right Side(R)&quot;, &quot;Right Side Center(…
## $ SHOT_ZONE_RANGE     &lt;chr&gt; &quot;8-16 ft.&quot;, &quot;16-24 ft.&quot;, &quot;16-24 ft.&quot;, &quot;8-16 ft.&quot;,…
## $ SHOT_DISTANCE       &lt;dbl&gt; 9, 22, 23, 8, 7, 1, 7, 3, 15, 8, 23, 16, 1, 0, 0,…
## $ LOC_X               &lt;dbl&gt; 36, 214, 129, 36, 26, -2, 69, 1, -11, 70, -229, 1…
## $ LOC_Y               &lt;dbl&gt; 93, 83, 194, 75, 75, 12, 28, 34, 156, 50, 37, 39,…
## $ SHOT_ATTEMPTED_FLAG &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ SHOT_MADE_FLAG      &lt;dbl&gt; 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1…
## $ GAME_DATE           &lt;dbl&gt; 20091027, 20091027, 20091027, 20091027, 20091027,…
## $ HTM                 &lt;chr&gt; &quot;CLE&quot;, &quot;CLE&quot;, &quot;CLE&quot;, &quot;CLE&quot;, &quot;CLE&quot;, &quot;CLE&quot;, &quot;CLE&quot;, …
## $ VTM                 &lt;chr&gt; &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, …</code></pre>
<pre class="r"><code>glimpse(dat4)</code></pre>
<pre><code>## Observations: 219,458
## Variables: 24
## $ GRID_TYPE           &lt;chr&gt; &quot;Shot Chart Detail&quot;, &quot;Shot Chart Detail&quot;, &quot;Shot C…
## $ GAME_ID             &lt;chr&gt; &quot;0021800001&quot;, &quot;0021800001&quot;, &quot;0021800001&quot;, &quot;002180…
## $ GAME_EVENT_ID       &lt;dbl&gt; 7, 10, 14, 17, 19, 21, 23, 25, 27, 29, 32, 35, 38…
## $ PLAYER_ID           &lt;dbl&gt; 203496, 1628369, 1627759, 203954, 1628369, 203967…
## $ PLAYER_NAME         &lt;chr&gt; &quot;Robert Covington&quot;, &quot;Jayson Tatum&quot;, &quot;Jaylen Brown…
## $ TEAM_ID             &lt;dbl&gt; 1610612755, 1610612738, 1610612738, 1610612755, 1…
## $ TEAM_NAME           &lt;chr&gt; &quot;Philadelphia 76ers&quot;, &quot;Boston Celtics&quot;, &quot;Boston C…
## $ PERIOD              &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ MINUTES_REMAINING   &lt;dbl&gt; 11, 11, 11, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9…
## $ SECONDS_REMAINING   &lt;dbl&gt; 40, 15, 3, 55, 36, 32, 22, 15, 6, 58, 36, 32, 19,…
## $ EVENT_TYPE          &lt;chr&gt; &quot;Missed Shot&quot;, &quot;Missed Shot&quot;, &quot;Missed Shot&quot;, &quot;Mad…
## $ ACTION_TYPE         &lt;chr&gt; &quot;Jump Shot&quot;, &quot;Jump Shot&quot;, &quot;Running Layup Shot&quot;, &quot;…
## $ SHOT_TYPE           &lt;chr&gt; &quot;3PT Field Goal&quot;, &quot;3PT Field Goal&quot;, &quot;2PT Field Go…
## $ SHOT_ZONE_BASIC     &lt;chr&gt; &quot;Above the Break 3&quot;, &quot;Above the Break 3&quot;, &quot;Restri…
## $ SHOT_ZONE_AREA      &lt;chr&gt; &quot;Center(C)&quot;, &quot;Left Side Center(LC)&quot;, &quot;Center(C)&quot;,…
## $ SHOT_ZONE_RANGE     &lt;chr&gt; &quot;24+ ft.&quot;, &quot;24+ ft.&quot;, &quot;Less Than 8 ft.&quot;, &quot;Less Th…
## $ SHOT_DISTANCE       &lt;dbl&gt; 26, 25, 1, 0, 4, 26, 2, 2, 1, 1, 3, 0, 15, 17, 2,…
## $ LOC_X               &lt;dbl&gt; -53, -148, 4, -8, -46, 177, -14, -9, -7, 5, -31, …
## $ LOC_Y               &lt;dbl&gt; 264, 207, 18, 3, 1, 193, 15, 21, 8, 19, 8, -6, 13…
## $ SHOT_ATTEMPTED_FLAG &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ SHOT_MADE_FLAG      &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1…
## $ GAME_DATE           &lt;dbl&gt; 20181016, 20181016, 20181016, 20181016, 20181016,…
## $ HTM                 &lt;chr&gt; &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, &quot;BOS&quot;, …
## $ VTM                 &lt;chr&gt; &quot;PHI&quot;, &quot;PHI&quot;, &quot;PHI&quot;, &quot;PHI&quot;, &quot;PHI&quot;, &quot;PHI&quot;, &quot;PHI&quot;, …</code></pre>
<p>For this project, my final dataset contains over 400,000 individual shots taken in the National Basketball Association for the 2009-2010, and 2018-2019. The data is stored in the nba_shots_2010.csv and the nba_shots_2019.csv. I compiled this data using an api based web scraper that uses the requests and json modules in python. The link to the web scraper template that I used is included below. The 2010 data consists of 200,966 observations of 24 variables. The 2019 data consists of 219,458 observations and 24 variables. The variables for each dataset are the same. GRID_TYPE is negligible, it is a class character with one unique value. GAME_ID, GAME_EVENT_ID, PLAYER_ID, and TEAM_ID are all either characters or numeric with the purpose of identifying some individual or event. PLAYER_NAME and TEAM_NAME are more useful versions of the ID variables, being stored as human readable characters. PERIOD identifies the current period when a given shot was taken, it is stored as a numeric. MINUTES_REMAINING and SECONDS_REMAINING in conjunction tell the amount of time remaining when the shot was taken and are stored as numerics. EVENT_TYPE tells whether the shot was a Missed Shot or a Made Shot and is stored as a character string. ACTION_TYPE describes the type of shot being taken, there are 45 different types of shots stored in the data, and they are stored as characters. Wow! SHOT_TYPE tells us whether a shot was a 3PT Field Goal, or a 2PT Field Goal stored as characters. SHOT_ZONE_BASIC, SHOT_ZONE_AREA, and SHOT_ZONE_DISTANCE quantify where the shot was taken in 7, 6, and 5 zones respectively. Stored as characters. LOC_X and LOC_Y are powerful variables that plot a shot’s location on a coordinate plane. They are numeric, as are SHOT_ATTEMPTED_FLAG, and SHOT_MADE_FLAG which are 0 or 1 and indicate the same information as other statistics. GAME_DATE, HTM, and VTM give information about the game where the shot was taken, and are stored as a numeric and two characters respectively.</p>
<ul>
<li><p>Task 1: First, I will detail the process of data allocation. I will then examine the strategy shakeup beautifully explained by Kirk Goldsberry in his book Sprawlball by examining relationships such as FGP over distance from basket, points per shot over distance from basket, and the change in shooting distributions from 2009-2019. Ggplot will be used in conjunction with cowplot for visualizations.</p></li>
<li><p>Task 2: Second, after giving the above relationships a good look, I will attempt to develop my very own basketball statistics. One statistic will be based solely on a teams efficiency in executing the Sprawlball strategy. It will resolve to a simple numeric value that can be evaluated on a continuous scale. The other statistic will attempt to predict outcomes at a better than random percentage (Tested by hypothesis test). I will do this by combining various elements such as points per possession, average FGP, average shot distance, and shot type.</p></li>
<li><p>Task 3: If possible, I hope to use my twitter developer access to build a twitter bot. This bot will interact with the twitter API and live web data to publish when a Sprawlball inspired event occurs. If my statistic evaluates to higher than a certain value the bot will automatically publish a tweet describing the game in question.</p></li>
</ul>
<p>The overarching purpose of this analysis is to again visited optimized strategy and its benefits.</p>
<p><a href="https://datavizardry.com/2020/01/28/nba-shot-charts-part-1/" class="uri">https://datavizardry.com/2020/01/28/nba-shot-charts-part-1/</a></p>
</div>
</div>
